apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lottery
spec:
  selector:
    app: nginx
    type: NodePort
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: 80
    protocol: TCP
